from pathlib import Path

from smartwave_ai.visual_analysis.config import BASE_DIR


DEFAULT_INCIDENT_STORE_PATH = BASE_DIR / "runtime" / "incident_reports.json"

REPORT_TYPE_WEIGHTS = {
    "ODOR_COMPLAINT": 1.0,
    "STRUCTURAL_DAMAGE": 2.5,
    "PEST_INFESTATION": 2.0,
    "FIRE_HAZARD": 5.0,
    "ILLEGAL_DUMPING": 1.5,
    "CONTAINER_MISSING": 3.0,
}

CITIZEN_REPORT_LIMIT_PER_24H = 3
DEVICE_REPORT_CLUSTER_LIMIT_PER_HOUR = 5

ODOR_AI_CORROBORATION_WINDOW_HOURS = 4
CONTAINER_MISSING_WINDOW_HOURS = 6

DEFAULT_VERIFIED_INCIDENT_ETA = "within 4 hours"

